
- name: github ansible test
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello Ansible Tower!! Success!! I've executed Ansible Enterprise Template from github (Non-enterprise project) I can run malicious scripts muahahahaha!!"
